<a href="https://colab.research.google.com/github/xmajax123/Data-Analyst-Prject-RBNB/blob/main/Projekt_ARBNB_M_Pochel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Opis zbioru danych

Zbiór danych zawiera informacje o ofertach Airbnb, m.in.:
- lokalizacji (dzielnica, współrzędne)
- cenie i opłacie serwisowej
- dostępności
- liczbie i ocenie recenzji
- zasadach wynajmu (house rules, instant bookable)

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Wczytanie danych

In [ ]:
dane= pd.read_excel('Airbnb.xlsx')

Podstawowe informacje o zbiorze danych:
a) rozmiar
b) nagłówki

In [ ]:
info=dane.head()
info

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,price,service fee,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,966.0,966.0,10.0,9.0,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,142.0,142.0,30.0,45.0,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,620.0,620.0,3.0,0.0,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,368.0,368.0,30.0,270.0,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,204.0,204.0,10.0,9.0,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [ ]:
wymiary=dane.shape
print(f'Wymiary danych to: {wymiary}')

Wymiary danych to: (102599, 25)

Nazwy kolumn:

In [ ]:
dane.columns
for col in dane.columns:
  print(col)

id
NAME
host id
host_identity_verified
host name
neighbourhood group
neighbourhood
lat
long
country
country code
instant_bookable
cancellation_policy
room type
Construction year
price
service fee
minimum nights
number of reviews
reviews per month
review rate number
calculated host listings count
availability 365
house_rules
license

TYPY DANYCH:

In [ ]:
summary = pd.DataFrame({"Nazwa kolumny":dane.columns,
                        "Typ danych": dane.dtypes,
                        "Brakujące wartości":dane.isnull().sum(),
                        "% brakujących danych":(dane.isnull().sum()/len(dane))*100,
                       "Unikatowe wartości": dane.nunique().values})
summary

,Nazwa kolumny,Typ danych,Brakujące wartości,% brakujących danych,Unikatowe wartości
id,id,int64,0,0.000000,102058
NAME,NAME,object,274,0.267059,61277
host id,host id,int64,0,0.000000,102057
host_identity_verified,host_identity_verified,object,289,0.281679,2
host name,host name,object,408,0.397665,13188
neighbourhood group,neighbourhood group,object,29,0.028265,7
neighbourhood,neighbourhood,object,16,0.015595,224
lat,lat,float64,8,0.007797,21991
long,long,float64,8,0.007797,17774
country,country,object,532,0.518524,1
country code,country code,object,131,0.127682,1
instant_bookable,instant_bookable,float64,105,0.102340,2
cancellation_policy,cancellation_policy,object,76,0.074075,3
room type,room type,object,0,0.000000,4
Construction year,Construction year,float64,214,0.208579,20
price,price,float64,247,0.240743,1151
service fee,service fee,float64,247,0.240743,1151
minimum nights,minimum nights,float64,409,0.398639,153
number of reviews,number of reviews,float64,183,0.178364,476
reviews per month,reviews per month,float64,15879,15.476759,1016
review rate number,review rate number,float64,326,0.317742,5
calculated host listings count,calculated host listings count,float64,319,0.310919,78
availability 365,availability 365,float64,448,0.436651,438
house_rules,house_rules,object,54843,53.453737,1968
license,license,object,102597,99.998051,1





## Czyszczenie danych

W ramach przygotowania danych:
- usunięto kolumnę `license` z powodu bardzo dużej liczby brakujących danych (~99%)
- brakujące wartości w kolumnie `reviews per month` zastąpiono zerem
  (brak recenzji oznacza brak aktywności)
- brakujące wartości w kolumnie `house_rules` zastąpiono pustym ciągiem znaków

In [ ]:
dane= dane.drop(columns=["license"])

In [ ]:
dane["house_rules"]=dane["house_rules"].fillna("")

In [ ]:
dane["reviews per month"]=dane["reviews per month"].fillna(0)

Unikatowe wartości dla neighbourhood :

---

In [ ]:
dane['country'].unique()
x=dane['neighbourhood'].unique()

neighbour_unique=pd.DataFrame({"Unique values: ": x})
print(neighbour_unique)

            Unique values:
0                Kensington
1                   Midtown
2                    Harlem
3              Clinton Hill
4               East Harlem
..                      ...
220            Breezy Point
221             Willowbrook
222               Glen Oaks
223         Gerritsen Beach
224  Chelsea, Staten Island

[225 rows x 1 columns]

Unikatowe wartości dla neighbourhood group:

In [ ]:
y=dane['neighbourhood group'].unique()
neighbour_group=pd.DataFrame({"Unique values: ": y})
print(neighbour_group)

  Unique values:
0        Brooklyn
1       Manhattan
2         brookln
3        manhatan
4          Queens
5             NaN
6   Staten Island
7           Bronx

## Pytania badawcze

W analizie skupiono się na odpowiedzi na następujące pytania:
1. Czy cena zależy od roku budowy budynku?
2. Czy lokalizacja (dzielnica) wpływa na cenę oraz liczbę recenzji?
3. Czy liczba recenzji jest powiązana z ich oceną?
4. Czy możliwość natychmiastowej rezerwacji (instant bookable) wpływa na cenę i popyt?
5. Czy opłata serwisowa różni się w zależności od segmentu cenowego?
6. Jakie cechy wyróżniają najdroższe i najtańsze oferty?

In [ ]:

avg=dane.groupby('Construction_year')['price'].mean()
mediana=dane.groupby('Construction_year')['price'].median()
min=dane.groupby('Construction_year')['price'].min()
max=dane.groupby('Construction_year')['price'].max()
std=dane.groupby('Construction_year')['price'].std()
summary_3=pd.DataFrame({'Średnia': avg, 'Mediana': mediana})
summary_3

KeyError: 'Construction_year'

In [ ]:
#rok budowy budynku  dla których wartości wynajmu Airbnb były najwieksze i najmniejsze
year_max=dane['price'].idxmax()
year_min=dane['price'].idxmin()
# max i min wartość srednia dla roku budowy
max_avg=dane['price'].max()
min_avg=dane['price'].min()


summary_1=pd.DataFrame({"Year":[year_max, year_min],
                     "Average": [max_avg,min_avg]})

summary_1

   Year  Average
0  2589   1200.0
1   360     50.0

In [ ]:
#rok budowy budynku  dla których wartości wynajmu Airbnb były najwieksze i najmniejsze
year_max=dane['price'].idxmax()
year_min=dane['price'].idxmin()
# max i min wartość srednia dla roku budowy
max_avg=avg.max()
min_avg=avg.min()


summary_1=pd.DataFrame({"Year":[year_max, year_min],
                     "Average": [max_avg,min_avg]})

summary_1

   Year     Average
0  2589  638.003067
1   360  612.613264


## Cena i recenzje w zależności od dzielnicy

Analiza wykazała istotne różnice cen pomiędzy dzielnicami.
Najdroższe oraz najtańsze oferty zlokalizowane są w różnych częściach miasta,
co sugeruje, że lokalizacja jest jednym z kluczowych czynników wpływających na cenę.

In [ ]:
averages=dane.groupby("neighbourhood")['price'].mean()
medians=dane.groupby("neighbourhood")['price'].median()
summary_4=pd.DataFrame({'Średnia': averages, 'Mediana':medians})
summary_4

                    Średnia  Mediana
neighbourhood
Allerton         636.343750    630.0
Arden Heights    804.888889    889.0
Arrochar         625.764706    629.0
Arverne          652.125561    676.0
Astoria          639.035275    645.0
...                     ...      ...
Windsor Terrace  579.784848    551.0
Woodhaven        630.518325    636.0
Woodlawn         587.137931    684.0
Woodrow          709.333333   1025.0
Woodside         634.588336    639.0

[224 rows x 2 columns]

Znalezienie w której okolicy sa najtansze i najdrozsze Airbnb

In [ ]:
avergae_max=averages.max()
avergae_min=averages.min()

med_max=medians.max()

med_min=medians.min()

idx1=averages.idxmax()
idx2=averages.idxmin()

summary_2=pd.DataFrame({"Neighbourhood":[idx1,idx2],
                     "Average price": [avergae_max,avergae_min],
                        'Median of price': [med_max,med_min]})

summary_2

     Neighbourhood  Average price  Median of price
0         New Dorp    1045.000000           1044.0
1  Lighthouse Hill     107.666667            127.0

In [ ]:
reviews_avg = dane.groupby('neighbourhood')['reviews per month'].mean()
reviews_median = dane.groupby('neighbourhood')['reviews per month'].median()
rating_avg = dane.groupby('neighbourhood')['review rate number'].mean()
rating_median = dane.groupby('neighbourhood')['review rate number'].median()

In [ ]:
summary_2['Avg amount of reviews'] = summary_2['Neighbourhood'].map(reviews_avg)
summary_2['Abg rating'] = summary_2['Neighbourhood'].map(rating_avg)
summary_2['Median rating']=summary_2['Neighbourhood'].map(rating_median)
summary_2

,Neighbourhood,Average price,Median of price,Avg amount of reviews,Abg rating,Median rating
0,New Dorp,1045.000000,1044.0,1.480000,3.250000,3.0
1,Lighthouse Hill,107.666667,127.0,1.246667,2.666667,3.0

In [ ]:
dane['review rate number'].unique()

array([ 4.,  5.,  3., nan,  2.,  1.])

In [ ]:
reviews_neighbourhood=dane.groupby('neighbourhood')['number of reviews'].count().sort_values(ascending=False)
reviews_neighbourhood.head(10)

neighbourhood
Bedford-Stuyvesant    7924
Williamsburg          7758
Harlem                5455
Bushwick              4969
Hell's Kitchen        3962
Upper West Side       3854
Upper East Side       3675
East Village          3488
Midtown               3383
Crown Heights         3261
Name: number of reviews, dtype: int64

In [ ]:
avg_rate=dane.groupby('neighbourhood')['review rate number'].mean().sort_values(ascending=False)

## Liczba recenzji a ich ocena

Stwierdzono, że większa liczba recenzji nie zawsze oznacza wyższą ocenę.
Przykładem jest dzielnica Bedford-Stuyvesant, która posiada dużą liczbę recenzji
pomimo relatywnie niskiej średniej oceny.
Może to świadczyć o dużym popycie wynikającym z czynników zewnętrznych,
takich jak lokalizacja lub dostępność komunikacyjna.

In [ ]:
reviews_neighbourhood = reviews_neighbourhood.reset_index()
averages = averages.reset_index()
avg_rate = avg_rate.reset_index()

In [ ]:
lat_df = dane[['neighbourhood', 'lat']].drop_duplicates()
long_df = dane[['neighbourhood', 'long']].drop_duplicates()

df_top10=pd.DataFrame(reviews_neighbourhood.head(10)).merge(averages, on='neighbourhood',how='left').merge(avg_rate,on='neighbourhood',how='left')
df_top10

        neighbourhood  number of reviews       price  review rate number
0  Bedford-Stuyvesant               7924  622.983462            3.281278
1        Williamsburg               7758  625.536488            3.247968
2              Harlem               5455  626.802419            3.230783
3            Bushwick               4969  633.338502            3.276056
4      Hell's Kitchen               3962  621.065388            3.281630
5     Upper West Side               3854  616.526862            3.241487
6     Upper East Side               3675  618.197383            3.252316
7        East Village               3488  617.498849            3.271839
8             Midtown               3383  609.547041            3.310171
9       Crown Heights               3261  617.531673            3.283958

# **WNIOSKI**
a) cena nie jest czynnikiem wpływającym na popyt

b) wartość recenzji wcale nie jest równoznaczna z ilością- największą ilość rencezji ma dzielnica Bedford-Stuversant. Co może oznaczać,że mimo  że mogą być nie najlepsze warunki,(ocena srednia 3,2) najwięcej ludzi tam rezerwuje - możliwe że wpływ ma na to odległość od metra, atrakcji czy centrum miasta bądź lotniska
Sprawdźmy więc to :

LICZYMY OUTLIERY
a) w cenie napewno
b) ilości recenzji

In [ ]:
q1=dane['price'].quantile(0.25)
q3=dane['price'].quantile(0.75)

IQR=q3-q1
lower=q1-1.5*IQR
upper=q3+1.5*IQR

analysis=pd.DataFrame({'Q1': [q1], 'Q3':[q3], 'IQR': [IQR], 'Lower bound': [lower], "Upper bound": [upper]})
analysis

      Q1     Q3    IQR  Lower bound  Upper bound
0  340.0  913.0  573.0       -519.5       1772.5

lower bound ustawiamy na 0 - nie ma ujemnych cen

In [ ]:
outliers=dane[(dane['price'] < 0) | (dane['price'] > upper)]
outliers

Empty DataFrame
Columns: [id, NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country, country code, instant_bookable, cancellation_policy, room type, Construction year, price, service fee, minimum nights, number of reviews, reviews per month, review rate number, calculated host listings count, availability 365, house_rules]
Index: []

[0 rows x 24 columns]

In [ ]:
q11=dane['reviews per month'].quantile(0.25)
q31=dane['reviews per month'].quantile(0.75)

IQR1=q31-q11
lower1=q11-1.5*IQR1
upper1=q31+1.5*IQR1

analysis1=pd.DataFrame({'Q1': [q11], 'Q3':[q31], 'IQR': [IQR1], 'Lower bound': [lower1], "Upper bound": [upper1]})
analysis1

outliers=dane[(dane['reviews per month'] < 0) | (dane['reviews per month'] > upper)]
outliers

Empty DataFrame
Columns: [id, NAME, host id, host_identity_verified, host name, neighbourhood group, neighbourhood, lat, long, country, country code, instant_bookable, cancellation_policy, room type, Construction year, price, service fee, minimum nights, number of reviews, reviews per month, review rate number, calculated host listings count, availability 365, house_rules]
Index: []

[0 rows x 24 columns]

INSTANT BOOKABLE VS LICZBA REZERWACJI I CENA

In [ ]:
dane['instant_bookable'].unique()

array([ 0.,  1., nan])

In [ ]:
dane['instant_bookable'].value_counts()

instant_bookable
0.0    51474
1.0    51020
Name: count, dtype: int64

**Service fee vs dwa zakresy cen**

tańsze (≤ mediana ceny)

droższe (> mediana ceny)

In [ ]:

price_median = dane['price'].median()

dane['price_range'] = pd.cut(
    dane['price'],
    bins=[0, price_median, dane['price'].max()],
    labels=['low_price_segment', 'high_price_segment']
)

service_fee_summary = (
    dane.groupby('price_range')['service fee']
        .agg(['mean','median','count'])
        .round(2)
        .reset_index()
)
service_fee_summary

/tmp/ipython-input-1715175306.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dane.groupby('price_range')['service fee']

          price_range    mean  median  count
0   low_price_segment  338.48   340.0  51183
1  high_price_segment  912.18   913.0  51169

więcej mamy rbnb bez możliwości instant book ale są podzielone 50/50

In [ ]:
avg_book=dane.groupby('instant_bookable')[['price','reviews per month', 'review rate number']].mean()

med_book=dane.groupby('instant_bookable')[['price','reviews per month', 'review rate number']].median()

summary_book = pd.concat([avg_book, med_book], axis=1)

summary_book

,price,reviews per month,review rate number,price,reviews per month,review rate number
instant_bookable,,,,,,
0.0,625.173813,1.371531,3.275258,626.0,0.74,3.0
1.0,625.397560,1.377200,3.282958,623.0,0.75,3.0

## Wpływ opcji instant bookable

Porównanie ofert z możliwością natychmiastowej rezerwacji oraz bez niej
nie wykazało istotnych różnic w cenie, liczbie recenzji ani ich ocenie.
Oznacza to, że funkcja instant bookable nie jest kluczowym czynnikiem
wpływającym na popyt ani cenę.

In [ ]:
dane['NAME']

0                       Clean & quiet apt home by the park
1                                    Skylit Midtown Castle
2                      THE VILLAGE OF HARLEM....NEW YORK !
3                                                      NaN
4         Entire Apt: Spacious Studio/Loft by central park
                                ...
102594                          Spare room in Williamsburg
102595                       Best Location near Columbia U
102596                      Comfy, bright room in Brooklyn
102597                    Big Studio-One Stop from Midtown
102598                                585 sf Luxury Studio
Name: NAME, Length: 102599, dtype: object

In [ ]:
top1_percent=dane['price'].quantile(0.990)
bottom_1_prct=dane['price'].quantile(0.01)
top_expensive=dane[dane['price']>=top1_percent]
bottom_cheap=dane[dane['price']<=bottom_1_prct]
columns=['NAME',"price","neighbourhood","reviews per month", "review rate number","room type","calculated host listings count"]

top_rbnb=top_expensive[columns].sort_values(by='price')
bottom_listings_table = bottom_cheap[columns].sort_values(by='price')

## Analiza skrajnych ofert (top 1%)

Porównano 1% najdroższych oraz 1% najtańszych ofert.
Różnice pomiędzy tymi grupami dotyczą przede wszystkim:
- ceny
- typu pokoju
- liczby ofert posiadanych przez hosta

In [ ]:

top_rbnb['Type'] = 'Top 1% najdroższych'
bottom_listings_table['Type'] = 'Top 1% najtańszych'


final_df = pd.concat([top_rbnb, bottom_listings_table], ignore_index=True)


final_df = final_df.sort_values(by='price', ascending=False)

final_df = final_df.reset_index(drop=True)
final_df

,NAME,price,neighbourhood,reviews per month,review rate number,room type,calculated host listings count,Type
0,Charming 1 bedroom in a 2 bedroom west village...,1200.0,West Village,0.00,3.0,Private room,1.0,Top 1% najdroższych
1,Big studio across the street from Prospect Park,1200.0,Prospect-Lefferts Gardens,1.28,5.0,Entire home/apt,1.0,Top 1% najdroższych
2,Book TODAY! Large 3br with lots of space in th...,1200.0,Belmont,3.17,4.0,Entire home/apt,3.0,Top 1% najdroższych
3,"Cozy room in bright, spacious apartment",1200.0,Hunts Point,0.00,2.0,Private room,4.0,Top 1% najdroższych
4,Private Room in Heart of Williamsburg!,1200.0,Williamsburg,0.00,3.0,Private room,2.0,Top 1% najdroższych
...,...,...,...,...,...,...,...,...
2146,Lovely Prospect Park 2BR With Yard,50.0,Flatbush,2.57,5.0,Entire home/apt,4.0,Top 1% najtańszych
2147,Great apt on the UWS - A RARE FIND!,50.0,Upper West Side,0.25,3.0,Entire home/apt,1.0,Top 1% najtańszych
2148,"Big, close to subway, 3 stops from the city",50.0,Astoria,0.31,1.0,Entire home/apt,1.0,Top 1% najtańszych
2149,BP- BEAUTIFUL COZY ROOM FOR 2 NEAR MANHATTAN ...,50.0,Borough Park,0.53,3.0,Private room,8.0,Top 1% najtańszych
2150,3rd Fl bright two bedroom,50.0,Bedford-Stuyvesant,0.50,3.0,Entire home/apt,9.0,Top 1% najtańszych

In [ ]:
dane.groupby('calculated host listings count')['number of reviews'].median().sort_index(ascending=False)

calculated host listings count
332.0     1.0
327.0     4.0
232.0     0.0
218.0     1.0
208.0    12.5
         ...
5.0      15.0
4.0      16.0
3.0      18.0
2.0      14.0
1.0       6.0
Name: number of reviews, Length: 78, dtype: float64

In [ ]:
dane[['calculated host listings count', 'number of reviews']].corr()

,calculated host listings count,number of reviews
calculated host listings count,1.000000,-0.080907
number of reviews,-0.080907,1.000000

In [ ]:
dane[['price','availability 365']].corr()

                     price  availability 365
price             1.000000         -0.002833
availability 365 -0.002833          1.000000

korelacja wynosi -0.08 korelacja ujemna choć bardzo mała, i tutaj bardziej pokazuje im więcej ma listingów tym mniej recenzji

In [ ]:
dane[['calculated host listings count', 'review rate number']].corr()

,calculated host listings count,review rate number
calculated host listings count,1.000000,0.024273
review rate number,0.024273,1.000000

korelacja wynosi 0,02 -> brak korelacji
czyli to ile pan ma rbnb nie wpływa na recenzje

In [ ]:
dane.groupby('room type')['price'].agg(['mean','median','count'])

                       mean  median  count
room type
Entire home/apt  625.082232   624.0  53568
Hotel room       668.465517   644.5    116
Private room     625.007363   623.0  46450
Shared room      634.132101   651.0   2218

In [ ]:

dane[['number of reviews','reviews per month']].corr()

                   number of reviews  reviews per month
number of reviews           1.000000           0.590939
reviews per month           0.590939           1.000000

## Korelacja liczby recenzji a średnia liczba recenzji miesięcznie

Analiza korelacji pokazuje umiarkowany związek (r = 0.59) między
łączną liczbą recenzji a średnią liczbą recenzji w miesiącu.
Oznacza to, że oferty z większą liczbą recenzji mają tendencję
do otrzymywania większej liczby recenzji miesięcznie, ale nie jest to regułą.
Wynik ten nie mówi nic o jakości ani ocenie recenzji.

## Normalizacja nazw kolumn

Wszystkie nazwy kolumn zostały zamienione na małe litery, usunięto spacje
i zamieniono je na podkreślniki, co ułatwia dalszą pracę z danymi w Pythonie.

In [ ]:
dane.columns = dane.columns.str.strip().str.lower().str.replace(' ', '_')
dane

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,...,service_fee,minimum_nights,number_of_reviews,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules,license,price_range
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,966.0,10.0,9.0,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN,high_price_segment
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,142.0,30.0,45.0,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN,low_price_segment
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,620.0,3.0,0.0,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN,low_price_segment
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,368.0,30.0,270.0,4.64,4.0,1.0,322.0,NaN,NaN,low_price_segment
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,204.0,10.0,9.0,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN,low_price_segment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,844.0,1.0,0.0,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN,high_price_segment
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,837.0,1.0,1.0,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN,high_price_segment
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,988.0,3.0,0.0,NaN,5.0,1.0,342.0,NaN,NaN,high_price_segment
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,546.0,2.0,5.0,0.10,3.0,1.0,386.0,NaN,NaN,low_price_segment
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,1032.0,1.0,0.0,NaN,3.0,1.0,69.0,NaN,NaN,high_price_segment

## Zapis oczyszczonego zbioru danych

Po wstępnym czyszczeniu danych zapisujemy je do pliku CSV,
aby mieć gotowy, uporządkowany zbiór do dalszej analizy.

In [ ]:
dane.to_csv("airbnb_clean123.csv", index=False)